---
- name: "update apt packages."
  become: yes
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: yes
  apt:
    upgrade: yes

# - name: remove dependencies that are no longer required
#   become: true
#   apt:
#     autoremove: yes

# - name: "install dependencies."
#   become: true
#   apt:
#     name: ["unzip", "curl"]
#     state: latest
#     update_cache: yes

# - name: "Install nodejs & npm"
#   become: true
#   shell: |
#     curl -sL https://deb.nodesource.com/setup_lts.x | sudo -E bash - && sudo apt-get install -y nodejs
#     node --version
#     npm --version

# - name: "Install PM2"
#   become: true
#   shell: |
#     npm i -g pm2

- name: "install dependencies."
  become: yes
  apt:
    name: ["nodejs", "npm", "unzip", "curl"]
    state: latest
    update_cache: yes

- name: "install pm2"
  become: yes
  npm:
    name: pm2
    global: yes
    production: yes
    state: present
