---

# - name: "Creates backend app directory"
#   file:
#       path: ~/backend-app
#       state: directory

# - name: "Copy compiled backend app"
#   copy:
#       src: dist.zip
#       dest: "~/backend-app/dist.zip"

# - name: "Unzip backend files"
#   shell: |
#       cd ~/backend-app
#       unzip dist.zip
#       rm -rf dist.zip

# - name: "Install dependencies"
#   shell: |
#       cd ~/backend-app
#       npm install --force
      
# - name: "Executing node"
#   shell: |
#       export
#       cd ~/backend-app
#       pm2 start main.js --update-env
#   register: execute_node

# - name: "print message"
#   debug:
#       msg: "{{ execute_node.stdout_lines }}"

# - name: "Configure pm2"
#   become: true
#   shell: |
#       env PATH=$PATH:/usr/local/bin pm2 startup systemd -u ubuntu --hp /home/ubuntu

- name: install tar
  become: true
  apt:
    name: tar
    state: latest
    update_cache: yes

- name: "Add nodejs 13.x"
  shell: |
    curl -fsSL https://deb.nodesource.com/setup_13.x | sudo -E bash 
    sudo apt-get install -y nodejs

- name: install pm2
  become: true
  npm:
    name: pm2
    global: yes
    state: latest
    production: yes

- name: copy built backend files
  become: true
  copy:
    src: artifact.tar.gz
    dest: /home/ubuntu

- name: Extract backend
  become: true
  shell: |
    cd /home/ubuntu
    tar -xzvf artifact.tar.gz

- name: "run server"
  become: true
  shell : |
      cd /home/ubuntu/
      npm install
      pm2 stop default
      pm2 start npm -- start
      