---

- name: install tar
  become: true
  apt:
    name: tar
    state: latest
    update_cache: yes

# - name: "Add nodejs 13.x"
#   shell: |
#     curl -fsSL https://deb.nodesource.com/setup_13.x | sudo -E bash 
#     sudo apt-get install -y nodejs

# - name: install pm2
#   become: true
#   npm:
#     name: pm2
#     global: yes
#     state: latest
#     production: yes

- name: copy built backend files
  become: true
  copy:
    src: artifact.tar.gz
    dest: /home/ubuntu

- name: Extract backend
  become: true
  shell: |
    cd /home/ubuntu
    tar -xzvf artifact.tar.gz

- name: "run server"
  become: true
  shell : |
      cd /home/ubuntu/
      npm install
      pm2 stop default
      pm2 start npm -- start
      